# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.prettyniceslice.com
title: Pretty Nice Slice
email: lara@prettyniceslice.com
author: Lara Moss
description: > # "Write an awesome description for your new site here. 
  Pretty Nice Slice, Home baked cakes in south East London, Brockley, Forest Hill, Catford
  baking rainbow cakes, cupcakes, bespoke cakes, birthday cakes, 
  description.
copyright: 'Copyright &copy; 2017 Lara Moss. All Rights Reserved.'

# ----------------------- #
#    Defaults             #
# ----------------------- #
defaults:
  - 
    scope:
      path: ""
    values:
      telephone:
        e164: "+447734702905"
        pretty: "07734 702905"
      location:
        latitude: 51.447017
        longitude: -0.035460
      mapbox:
        api_key: 'pk.eyJ1IjoibWFydHl6ejEiLCJhIjoiY2oxcm9iOGl5MDAwNTJ3bXcyeWdiNjlmNiJ9.JDrNea7qCgnK7-lObr3N_g'
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-maps

maps:
  google:
    api_key: AIzaSyB9Ht0M0Wx6DmTQNOZSy0qcCd7UZVYW-uY

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    icon: instagram
    url: https://instagram.com/prettyniceslice
  - title: facebook
    icon: facebook
    url: https://fb.me/prettyniceslice
  - title: email
    icon: envelope
    url: mailto:lara@prettyniceslice.com

